name: riceapp
description: UNIDO AfricaRice Quality Assessment Mobile App
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image: ^4.2.0
  path_provider: ^2.1.4
  path: ^1.9.0
  sqflite: ^2.3.3+1
  uuid: ^4.5.1
  csv: ^6.0.0
  share_plus: ^10.0.2
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  onnxruntime: ^1.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/rice_model.onnx
    - assets/models/m_stats.json
    - assets/models/model_version.txt
